### ISSUE TITLE
Pylint is not using project's `.pylintrc` unless pylsp is configured to run pylint via executable

### ISSUE THREAD

**Issue by b0o** [python-lsp/python-lsp-server#251] opened 2022-08-11 06:28 UTC
When I run pylint directly, it detects and uses the project's `.pylintrc`:

```
$ pylint -j0 my_module.py
```

My issue is that when I have pylsp configured like so, pylint does not use my `.pylintrc`:

```lua
pylsp = {
  plugins = {
    pylint = {
      enabled = true,
      args = { '-j0' },
    },
  },
},
```

However, with the following pylsp configuration, pylint does use the `.pylintrc`:

```lua
pylsp = {
  plugins = {
    pylint = {
      enabled = true,
      args = { '-j0' },
      executable = 'pylint',
    },
  },
},
```

I'm using Neovim with lspconfig as my LSP client.

**Comment by bagel897** [comment] 2022-08-25 01:27
See #238

**Comment by ccordoba12** [comment] 2022-08-27 16:04
Hey @b0o, thanks for reporting. As @bageljrkhanofemus mentioned, this is a duplicate of issue #238, so I'm going to close it.

You're welcome to send us a pull request to add support for it.

**Closed as completed by ccordoba12** 2022-08-27 16:04 UTC
