### ISSUE TITLE
file path auto completion add \ in path string

### ISSUE THREAD

**Issue by troubadour-hell** [python-lsp/python-lsp-server#373] opened 2023-04-26 15:08 UTC
Hello!I use jupyterlab-lsp with python-lsp-server. When I try to type in a file path, the auto-completion adds an \ before the last /, and it can't suggest the contents in this directory. 
![image](https://user-images.githubusercontent.com/17946453/234619084-6b1796a2-136a-4e9f-88c7-2dddbb5015c3.png)
![image](https://user-images.githubusercontent.com/17946453/234619107-ebad843c-2f75-4147-81c2-0ee5cf63c79f.png)
I find this:
https://github.com/python-lsp/python-lsp-server/blob/59856af9e7c3859d45133b79e02d1d7210fd50b3/pylsp/plugins/jedi_completion.py#L234
When I Removed "\\\\" from this line, it worked well. I'm not sure why it do this...

**Comment by ccordoba12** [comment] 2023-04-26 18:14
Hey @troubadour-hell, thanks for reporting. I think this problem depends on the way JupyterLab-LSP processes paths that come from this server.

@krassowski, thoughts about this?

**Comment by krassowski** [comment] 2023-04-26 21:28
For background, these changes were introduced 3 months ago in https://github.com/python-lsp/python-lsp-server/pull/337

I do not understand why the slashes there are escaped; my first expectation would be that no escaping should be needed on the server level and if escaping is needed for display then it is the clients' responsibility. Can you elaborate on the reasoning?

**Comment by ccordoba12** [comment] 2023-04-27 16:19
Here you can find the reasoning: https://github.com/palantir/python-language-server/pull/762 (see the PR description).

**Comment by krassowski** [comment] 2023-05-06 13:45
So the rationale is to prevent conflicts with snippet grammar which uses escapes. In that case it should be only escaped when [`CompletionClientCapabilities`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionClientCapabilities) include `completionItem.snippetSupport`.

**Comment by ccordoba12** [comment] 2023-05-06 15:49
Yep, I agree with that. Could you submit a PR for it?

**Comment by rchl** [comment] 2023-05-06 18:27
I might not have that much context about this issue and I don't know what kind of values can be provide through those completions but I would think that either:
a) those completions can contain snippet replacements in which case it wouldn't really be correct to provide those to a client that doesn't support snippets. So in that case those should always be escaped if client supports snippets and just omitted if it doesn't.
b) those completions never contain snippet replacements in which case those should just not be marked as having a snippet type and never escaped.

**Comment by ccordoba12** [comment] 2023-05-08 18:27
> a) those completions can contain snippet replacements in which case it wouldn't really be correct to provide those to a client that doesn't support snippets. So in that case those should always be escaped if client supports snippets and just omitted if it doesn't.

Right, that's what @krassowski suggested we should do to solve this problem.

**Closed as completed** 2023-12-12 03:59 UTC
Labels: bug

**Comment by vdualb** [comment] 2024-02-09 10:00
do I understand right that this issue is fixed in 1.10? I can reproduce it using helix editor. I previously reported this issue to them: https://github.com/helix-editor/helix/issues/9575.

I checked version this way:
```
(.venv) ⬢ image_compare pylsp --version
pylsp v1.10.0
```

**Comment by pascalkuthe** [comment] 2024-02-09 12:15
Helix supports snippet so this fix does not apply to us. The LSP standard does not List `\/` as a valid escape in snippets.

`\/` is only a valid escape inside a regex. So in most situations `\/` will be printer verbatim by VSCode and helix. Most likely printing `\/` instead of `/` should just be reverted. 

If you do actually use a regex in your snippets then you need to retroactively escape slashes when you generate the regex (or control that using somekind of flag)
