### ISSUE TITLE
[FEATURE REQUEST] Diagnostics for full project

### ISSUE THREAD

**Issue by albilu** [python-lsp/python-lsp-server#395] opened 2023-06-18 12:47 UTC
Hi there,

Is there any chance that `pylsp` will at some point implement a switch for diagnostics for the full workspace, as mentioned for `pyright` in this comment https://github.com/python-lsp/python-lsp-server/issues/143#issuecomment-1004906085 ?

E.g. for static type checkers like `mypy` it does make sense to see possible bad side effects of changes in type declarations in other files. And it would be useful in general too, e.g. for activating it just before pushing a large change.

Thanks for the great work!

_Originally posted by @JesusTorrado in https://github.com/python-lsp/python-lsp-server/discussions/280_

It will be great to have this feature wich will benefit all clients using this LSP server.

**Comment by ccordoba12** [comment] 2023-06-18 16:42
Closing as a duplicate of discussion #280 (I don't understand why you reposted the original comment from there here).

**Closed as completed by ccordoba12** 2023-06-18 16:42 UTC

**Comment by albilu** [comment] 2023-06-18 19:47
@ccordoba12  I litteraly asked in that discussion if it was ok to open the topic as feature request!. 

Are Feature request handle in discussions? What is the proper way to ask for a feature for this project??

**Comment by ccordoba12** [comment] 2023-06-18 22:41
It doesn't matter that much if that's a discussion or a feature request. What's needed is someone from the community willing to implement that functionality because we don't have time to do it.
