### ISSUE TITLE
DocumentSymbolsRequest responds with deprecated SymbolInformation

### ISSUE THREAD

**Issue by huppyflup** [python-lsp/python-lsp-server#396] opened 2023-06-20 21:04 UTC
When `document symbol request` is send python-lsp responds with `SymbolInformation`.

Specs say:
- "Servers should whenever possible return DocumentSymbol" [textDocument_documentSymbol](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentSymbol) and
- [symbolInformation](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#symbolInformation) deprecates the use of `SymbolInformation`

There is another issue that could be resolved with a change to `DocumentSymbol` https://github.com/python-lsp/python-lsp-server/issues/110

Are there plans to change the response to DocumentSymbol in a new release?

**Comment by ccordoba12** [comment] 2023-06-21 16:58
Hey @huppyflup, thanks for reporting. This is a duplicate of issue #110, as you pointed out.

**Closed as completed by ccordoba12** 2023-06-21 16:58 UTC
