### ISSUE TITLE
Deprecation of clients`resolved_capabilities` help

### ISSUE THREAD

**Issue by dmatos2012** [python-lsp/python-lsp-server#247] opened 2022-07-16 14:57 UTC
Hi everyone, 

First of all, `pylsp` has been running great and its been top. 

However, i switched my configuration from `nvim 0.7` to the development `nvim 0.8`, on which `client.resolved_capabilities` has been deprecated in lieu of `client.server_capabilities`. (see [issue](https://github.com/neovim/neovim/issues/14090#issuecomment-1113956767) ). Problem is, now I get a visual notification that trying to access it, its deprecated every time I open a python file, so its slightly annoying. 

To be honest, I am not not 100% sure the issue is pylsp or some other dependency pylsp depends on. I have been trying to figure it out on my own, but I am not sure. 

Any tips, or should I just wait till pylsp supports this? 

Any help would be greatly appreciated, and thanks for the lsp!

**Comment by SirSilver** [comment] 2022-07-18 10:14
This is issue with your nvim configuration, you should replace `client.resolved_capabilities` with `client.server_capabilities` somewhere in your LSP config file

**Comment by dmatos2012** [comment] 2022-07-18 10:23
Well, I disable `pylsp=false` in my lsp config and the warning goes away, and only coming back when `pylsp=true`, and I do not see it anywhere in my lsp config(checked with grep), but if you are telling me its not related to this repo, I am probably missing something, as its often the case. 

So feel free to close if this is irrelevant to this repo. Thank you!

**Comment by ccordoba12** [comment] 2022-07-20 14:52
This problem could also be caused by the way the Neovim client is configured to talk to this server.

Since I don't think it belongs here, I'm going to close it.

**Closed as completed by ccordoba12** 2022-07-20 14:52 UTC
