### ISSUE TITLE
Failed to load hook pylsp_lint: too many values to unpack (expected 3)

### ISSUE THREAD

**Issue by ptracton** [python-lsp/python-lsp-server#332] opened 2023-01-06 18:47 UTC
2023-01-06 12:21:26,264 CST - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 3
2023-01-06 12:21:26,267 CST - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 2
2023-01-06 12:21:27,063 CST - WARNING - pylsp.config.config - Failed to load hook pylsp_lint: too many values to unpack (expected 3)
Traceback (most recent call last):
  File "/user/tractp1/.local/lib/python3.8/site-packages/pylsp/config/config.py", line 33, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/user/tractp1/.local/lib/python3.8/site-packages/pluggy/_manager.py", line 327, in traced_hookexec
    return outcome.get_result()
  File "/user/tractp1/.local/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/user/tractp1/.local/lib/python3.8/site-packages/pluggy/_result.py", line 33, in from_call
    result = func()
  File "/user/tractp1/.local/lib/python3.8/site-packages/pluggy/_manager.py", line 324, in <lambda>
    lambda: oldcall(hook_name, hook_impls, kwargs, firstresult)
  File "/user/tractp1/.local/lib/python3.8/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/user/tractp1/.local/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/user/tractp1/.local/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/user/tractp1/.local/lib/python3.8/site-packages/pylsp/plugins/pydocstyle_lint.py", line 69, in pylsp_lint
    for filename, checked_codes, ignore_decorators in conf.get_files_to_check():
ValueError: too many values to unpack (expected 3)

This is on a RHEL8 system with emacs-30.0.5.  
python-3.8.10
python-jsonrpc-server==0.4.0
python-language-server==0.36.2
python-lsp-jsonrpc==1.0.0
python-lsp-server==1.7.0
pytoolconfig==1.2.4

**Comment by ccordoba12** [comment] 2023-01-06 23:16
Hey @ptracton, thanks for reporting. This is a bug caused by an API change in Pydocstyle 6.2 and I already fixed it in PR #329.

This will be part of pylsp 1.7.1. In the meantime, please use Pydocstyle 6.1.1.

**Closed as completed by ccordoba12** 2023-01-06 23:16 UTC
