### ISSUE TITLE
When running vim.lsp.buf.code_action() I get an error

### ISSUE THREAD

**Issue by mcepl** [python-lsp/python-lsp-server#146] opened 2022-01-02 21:15 UTC
When running `vim.lsp.buf.code_action()` with neovim 0.6.1 (from the commit https://github.com/neovim/neovim/commit/838631e29ef3051d6117b3d5c340d2be9f1f29b4) and python-lsp-server 1.3.3 I get this erorr:
```
pylsp: -32602: TypeError: m_workspace__execute_command() got an unexpected keyword argument
 'title'
```

**Comment by ccordoba12** [comment] 2022-01-03 14:39
According to the protocol:

https://microsoft.github.io/language-server-protocol/specification#workspace_executeCommand

`executeCommand` accepts a `command` and some `options` for it, not `title`, which is what Neovim seems to be sending. So this error seems to be on the Neovim side and not here.

**Comment by mjlbach** [comment] 2022-01-04 02:01
What's an example code action? Our code actions work with other language servers so I will need to see exactly what is going on. We're not explicitly passing title anywhere, my only guess would be as part of the diagnostics.

**Comment by mcepl** [comment] 2022-01-04 06:12
I have installed https://build.opensuse.org/package/show/devel:languages:python/python-pylsp-isort (aka https://github.com/paradoxxxzero/pyls-isort) so I asked neovim to Organize imports.

**Comment by mjlbach** [comment] 2022-01-04 07:59
Still having a bit of trouble. Can you provide a minimal init.lua reproducing the issue? I installed pyls-isort, and triggered vim.lsp.buf.code_action on an unsorted python file and am still not getting any code actions.

**Comment by mcepl** [comment] 2022-01-04 10:59
See my LSP configuration at https://mcepl.fedorapeople.org/tmp/lsp_servers.lua (requires https://github.com/kosayoda/nvim-lightbulb).

**Comment by mcepl** [comment] 2022-01-04 11:11
Log file is [pylsp-log.txt](https://github.com/python-lsp/python-lsp-server/files/7807126/pylsp-log.txt)

**Comment by mcepl** [comment] 2022-01-04 13:52
Hmm, so it is probably something done by `pylsp-rope`, right? @lieryan, what do you think?

**Comment by mjlbach** [comment] 2022-01-04 15:57
I'd prefer a reproduction with our minimal init.lua, in a repo with a python file that reproduces the issue, a requirements.txt with versioned python-lsp-server and all the plugins necessary, and a readme that specifies where/which request I need to send to reproduce the issue.

**Comment by lieryan** [comment] 2022-01-06 05:18
@mcepl: do you have the latest version of pylsp-rope installed? Some of the the earlier versions of pylsp-rope does certain things that works with some LSP clients but aren't strictly compliant to spec, which causes some issues with some clients that are more strict.

As far as I can tell, most of these bugs that I'm aware of should've already been fixed in latest version of python-rope, but it's possible there's yet another aspect of the LSP protocol that I misinterpreted.

**Comment by mcepl** [comment] 2022-01-06 07:37
Yup, 0.1.8 from the GitHub tarball.

**Comment by Akeboshiwind** [comment] 2022-01-08 00:13
I've got the same issue, I've built some sort of minimal_init.lua file (based of the one from nvim-lspconfig):

<details>
<summary>minimal_init.lua</summary>

```lua
local on_windows = vim.loop.os_uname().version:match 'Windows'

local function join_paths(...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir = vim.loop.os_getenv 'TEMP' or '/tmp'

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local install_path = join_paths(package_root, 'packer', 'start', 'packer.nvim')
local compile_path = join_paths(install_path, 'plugin', 'packer_compiled.lua')

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'neovim/nvim-lspconfig',
      'williamboman/nvim-lsp-installer', -- <-- Added for convenience
    },
    config = {
      package_root = package_root,
      compile_path = compile_path,
    },
  }
end

_G.load_config = function()
  vim.lsp.set_log_level 'trace'
  if vim.fn.has 'nvim-0.5.1' == 1 then
    require('vim.lsp.log').set_format_func(vim.inspect)
  end
  local nvim_lsp = require 'lspconfig'
  local on_attach = function(_, bufnr)
    local function buf_set_keymap(...)
      vim.api.nvim_buf_set_keymap(bufnr, ...)
    end
    local function buf_set_option(...)
      vim.api.nvim_buf_set_option(bufnr, ...)
    end

    buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

    -- Mappings.
    local opts = { noremap = true, silent = true }
    buf_set_keymap('n', 'gD', '<Cmd>lua vim.lsp.buf.declaration()<CR>', opts)
    buf_set_keymap('n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
    buf_set_keymap('n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
    buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
    buf_set_keymap('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
    buf_set_keymap('n', '<space>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opts)
    buf_set_keymap('n', '<space>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
    buf_set_keymap('n', '<space>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
    buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
    buf_set_keymap('n', '<space>e', '<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>', opts)
    buf_set_keymap('n', '[d', '<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>', opts)
    buf_set_keymap('n', ']d', '<cmd>lua vim.lsp.diagnostic.goto_next()<CR>', opts)
    buf_set_keymap('n', '<space>q', '<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>', opts)

    buf_set_keymap('n', 'T', '<cmd>lua vim.lsp.buf.code_action()<CR>', opts)
  end

  -- -- Add the server that troubles you here
  -- local name = 'pylsp'
  -- local cmd = { 'pyright-langserver', '--stdio' } -- needed for elixirls, omnisharp, sumneko_lua
  -- if not name then
  --   print 'You have not defined a server name, please edit minimal_init.lua'
  -- end
  -- if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
  --   print [[You have not defined a server default cmd for a server
  --     that requires it please edit minimal_init.lua]]
  -- end

  -- nvim_lsp[name].setup {
  --   cmd = cmd,
  --   on_attach = on_attach,
  -- }

  ------------- Added -------------

  local lsp_installer = require("nvim-lsp-installer")

  lsp_installer.settings({
      install_root_dir = join_paths(temp_dir, 'nvim', 'data', 'lsp_servers')
  })

  local ok, server = lsp_installer.get_server("pylsp")
  if not ok then
      error("Uh oh")
  end

  if not server:is_installed() then
      server:install()
  end

  server:on_ready(function ()
      server:setup({
          on_attach = function (client, bufnr)
              -- A tiny bit of a hack, don't look too hard
              local default_options = server:get_default_options()
              local PylspInstall = default_options.commands.PylspInstall[1]

              -- Install pylsp-rope plugin
              PylspInstall(
                  "pylsp-rope"
              )

	      on_attach(client, bufnr)
          end
      })
  end)

  ----------------------------------

  print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
  _G.load_config()
end
```

</details>

For convinience I've used `nvim-lsp-installer` to install everything (it also includes a command to install python packages in the right environment).

To recreate the issue I can:
1. `nvim -nu minimal_init.lua main.py`
2. Wait a little bit for things to install and press `q` to exit the installer menu
3. Press `T` (the keybind I setup for code_actions)
4. Select the any of the options, say by typeing `1` and hitting enter

I then get:
`pylsp: -32602: TypeError: m_workspace__execute_command() got an unexpected keyword argument 'title'`

I hope this helps :)

**Comment by mjlbach** [comment] 2022-01-08 00:25
It looks like pylsp rope is returning title in the result from the rpc request which we are bouncing back:

```lua
[DEBUG][2022-01-07 16:23:58] .../vim/lsp/rpc.lua:454	"rpc.receive"	{
  id = 8,
  jsonrpc = "2.0",
  result = { {
      command = {
        arguments = { {
            document_uri = "file:///Users/michael/Repositories/ray/doc/examples/cython/cython_main.py",
            global_ = false,
            range = {
              end = {
                character = 0,
                line = 2
              },
              start = {
                character = 0,
                line = 2
              }
            },
            similar = true
          } },
        command = "pylsp_rope.refactor.extract.method",
        title = "Extract method including similar statements"
      },
      kind = "refactor.extract",
      title = "Extract method including similar statements"
    }, {
      command = {
        arguments = { {
            document_uri = "file:///Users/michael/Repositories/ray/doc/examples/cython/cython_main.py",
            global_ = false,
            range = {
              end = {
                character = 0,
                line = 2
              },
              start = {
                character = 0,
                line = 2
              }
            },
            similar = false
          } },
        command = "pylsp_rope.refactor.extract.method",
        title = "Extract method"
      },
      kind = "refactor.extract",
      title = "Extract method"
    }, {
      command = {
        arguments = { {
            document_uri = "file:///Users/michael/Repositories/ray/doc/examples/cython/cython_main.py",
            global_ = true,
            range = {
              end = {
                character = 0,
                line = 2
              },
              start = {
                character = 0,
                line = 2
              }
            },
            similar = true
          } },
        command = "pylsp_rope.refactor.extract.method",
        title = "Extract global method including similar statements"
      },
      kind = "refactor.extract",
      title = "Extract global method including similar statements"
    }, {
      command = {
        arguments = { {
            document_uri = "file:///Users/michael/Repositories/ray/doc/examples/cython/cython_main.py",
            global_ = true,
            range = {
              end = {
                character = 0,
                line = 2
              },
              start = {
                character = 0,
                line = 2
              }
            },
            similar = false
          } },
        command = "pylsp_rope.refactor.extract.method",
        title = "Extract global method"
      },
      kind = "refactor.extract",
      title = "Extract global method"
    }, {
      command = {
        arguments = { {
            document_uri = "file:///Users/michael/Repositories/ray/doc/examples/cython/cython_main.py",
            position = {
              character = 0,
              line = 2
            }
          } },
        command = "pylsp_rope.refactor.local_to_field",
        title = "Convert local variable to field"
      },
      kind = "refactor.rewrite",
      title = "Convert local variable to field"
    }, {
      command = {
        arguments = { {
            document_uri = "file:///Users/michael/Repositories/ray/doc/examples/cython/cython_main.py"
          } },
        command = "pylsp_rope.source.organize_import",
        title = "Organize import"
      },
      kind = "source.organizeImports",
      title = "Organize import"
    } }
}
[DEBUG][2022-01-07 16:23:59] .../lua/vim/lsp.lua:993	"LSP[pylsp]"	"client.request"	1	"workspace/executeCommand"	{
  arguments = { {
      document_uri = "file:///Users/michael/Repositories/ray/doc/examples/cython/cython_main.py"
    } },
  command = "pylsp_rope.source.organize_import",
  title = "Organize import"
}	<function 1>	1
[DEBUG][2022-01-07 16:23:59] .../vim/lsp/rpc.lua:347	"rpc.send"	{
  id = 9,
  jsonrpc = "2.0",
  method = "workspace/executeCommand",
  params = {
    arguments = { {
        document_uri = "file:///Users/michael/Repositories/ray/doc/examples/cython/cython_main.py"
      } },
    command = "pylsp_rope.source.organize_import",
    title = "Organize import"
  }
}
```

(also side note, in the future please do not use nvim-lsp-installer for minimal repos, I usually have to spend the time to pull it out of the example as it requires an ugly wrapper around lspconfig)

**Comment by mjlbach** [comment] 2022-01-08 00:31
I think we're correct in sending the title back:

`codeAction/resolve` requests
https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#codeAction_resolve
send codeAction params https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#codeAction which can include the string.

**Comment by mjlbach** [comment] 2022-01-08 00:55
This will fix it https://github.com/neovim/neovim/pull/16987

You can close the issue here. We're not filtering out title from the code action response.

**Comment by ccordoba12** [comment] 2022-01-08 02:48
Great! Closing then.

**Closed as completed by ccordoba12** 2022-01-08 02:48 UTC

**Comment by mcepl** [comment] 2022-01-08 08:10
Seems to work well. Thank you.
