### ISSUE TITLE
Support for textDocument/documentSymbol ?

### ISSUE THREAD

**Issue by dsully** [python-lsp/python-lsp-server#74] opened 2021-08-28 16:26 UTC
Although I see:

```
'documentSymbolProvider': True,
```

Specified in `pylsp/python_lsp.py`, it doesn't appear to return the hierarchy as specified by `documentSymbol`: https://microsoft.github.io/language-server-protocol/specification#textDocument_documentSymbol

See this related issue for a Neovim plugin: https://github.com/simrat39/symbols-outline.nvim/issues/48

**Comment by ccordoba12** [comment] 2021-08-28 17:56
We're using the document symbol support here successfully in Spyder:

![imagen](https://user-images.githubusercontent.com/365293/131226664-48ad2fb5-35e1-4555-909d-40d2e9e66daf.png)

So I don't understand what's missing.

**Comment by dsully** [comment] 2021-09-25 14:06
It looks like the difference here is `pyright` uses the `children` hierarchy, while `pylsp` uses `containerName`.

See the comment here: https://github.com/simrat39/symbols-outline.nvim/issues/48#issuecomment-927104234

**Comment by ccordoba12** [comment] 2021-11-05 14:13
Closing this as a duplicate of #110 because it has more info.

**Closed as completed by ccordoba12** 2021-11-05 14:13 UTC
