### ISSUE TITLE
Project-level linter configuration files not working

### ISSUE THREAD

**Issue by StefanBrand** [python-lsp/python-lsp-server#54] opened 2021-07-12 13:22 UTC
_This is a follow-up from https://github.com/krassowski/jupyterlab-lsp/issues/633._

___
# Expected behaviour
Config files such as `setup.cfg` are read from same directory where notebook resides (or parent directories).

# Actual behaviour
Config files are only picked up from home directory

# Steps to reproduce
1. Create `setup.cfg` in a new folder:
```
[flake8]
ignore = E402
```

2. Create a notebook in the same folder:
```
foo = "bar"

import json
```

3. Observe: module level import not at top of file
![image](https://user-images.githubusercontent.com/8948865/125294361-7c612080-e324-11eb-861a-8bb836f507c8.png)
4. Move `setup.cfg` to home:  `mv setup.cfg ~`
5. Re-open notebook
6. Observe: No issues detected!
![image](https://user-images.githubusercontent.com/8948865/125294586-add9ec00-e324-11eb-975c-a8f35bbde24a.png)

**Comment by krassowski** [comment] 2021-07-12 13:26
I think `setup.cfg` should be in the same directory that you start JupyterLab from. On the screenshots above you put it into a sub-directory, which was not clear to me in the previous issue.

**Comment by StefanBrand** [comment] 2021-07-12 13:35
What about [this line](https://github.com/python-lsp/python-lsp-server/blob/87b76d791dc3fd2e2f229c7f8c4898ce06c352e9/pylsp/config/config.py#L100) in the docstring? 

>             4. Project settings, found in config files in the current project.

`document_path` also seems to indicate to me that the notebook's path is involved in the configuration search.

**Comment by krassowski** [comment] 2021-07-12 13:46
Yes, but the `jupyter-`lsp extension does not pass true paths of the notebooks to `pylsp` because notebooks do not exist as python files on disk (yet rope which is used by `pylsp` for example requires a real file on the disk). So this will not work like that currently. However, if you start the JupyterLab client in `test` directory then it should work ok (if it does not this is a bug).

**Comment by StefanBrand** [comment] 2021-07-12 14:04
Ok, understood! I can confirm that `setup.cfg` works in the directory where JupyterLab is started from. 

Unfortunately I cannot choose which directory to start JupyterLab from as it is running in JupyterHub. I log in to JupyterHub and work from there. However we can probably ship the `setup.cfg` together with the Docker image running in JupyterHub. :thinking:

**Comment by krassowski** [comment] 2021-07-12 15:58
Thanks for getting back to me. I will close this one as we confirmed that all is good on `python-lsp-server` side and re-open the issue in `jupyterlab-lsp` repository instead.

**Closed as completed by krassowski** 2021-07-12 15:58 UTC
